export const ORDER_REPOSITORY_TOKEN = Symbol('ORDER_REPOSITORY_TOKEN');
export const PATIENT_SNAPSHOT_REPOSITORY_TOKEN = Symbol('PATIENT_SNAPSHOT_REPOSITORY_TOKEN');
export const PATIENT_QUERY_SERVICE_TOKEN = Symbol('PATIENT_QUERY_SERVICE_TOKEN');
